# Fix FTP credential problem when updating theme. 
# https://github.com/docker-library/wordpress/issues/298
version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db:/var/lib/mysql

  wordpress:
    links: 
      - mysql
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - 100:80
    environment: 
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./wordpress:/var/www/html

volumes:
  db:
  wordpress:
